name: LBYangin
version: '1.0-SNAPSHOT'
main: com.lbdevz.lbyangin.LBYangin
api-version: '1.21'
author: xCatyy

commands:
  yangin:
    description: LB-Yangin ana komutu
    permission: lbyangin.admin
    usage: /yangin [start|stop|reload]