settings:
  ghast-amount: 4
  ghast-health: 100.0
  ghast-glowing: true
  fire-radius: 2
  shoot-interval-seconds: 3
  explosion-enabled: true
  explosion-power: 3.0
  bossbar-title: "&c&lYANGIN ETKİNLİĞİ &7- &eGhast Canı"
  bossbar-color: "RED" # RED, PINK, PURPLE, WHITE, UNKNOWN, GREEN, BLUE

rewards:
  # Etkinlik bittiğinde tüm oyunculara çalıştırılacak komut (%player% dinamiktir)
  command: "crate givekey %player% yangin 1"

messages:
  prefix: "&a[LB-Yangin] "
  event-end: "&fTüm Ghast'lar temizlendi! Etkinlik başarıyla tamamlandı, ödüller dağıtıldı!"
  config-reloaded: "&aKonfigürasyon başarıyla yeniden yüklendi."

warp-location:
  world: "world"
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0