name: LBYangin
version: '1.1'
main: com.lbdevz.lbyangin.LBYangin
api-version: '1.20'
authors: [LBDevz]
description: MC Yangin Etkinligi Eklentisi

commands:
  yangin:
    description: Yangin etkinligi ana komutu
    permission: lbyangin.admin
    usage: /yangin <start|stop|setwarp>